# Generated by Django 3.1.2 on 2020-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=75)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('postImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
