# Generated by Django 3.1.2 on 2020-12-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postImage',
            field=models.ImageField(upload_to='static/tmp/'),
        ),
    ]
